version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - MONGO_URI=mongodb+srv://mayconpachecooficial:ziGB7Oq1OufcSCTO@devpacheco.0qawp3m.mongodb.net/?retryWrites=true&w=majority&appName=devpacheco
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
